### ISSUE TITLE
add showDelay for touch event

### ISSUE THREAD

**Issue by koshak01** [i-like-robots/EasyZoom#83] opened 2016-01-11 21:02 UTC
when i click image in iphone - fire zoom event - and i can scroll ((((( 

can you put showDelay option in touch 

if i pull 5 sec on image - fire zoom event
if i scroll - ( fast touch ) - then scroll event 

tnx

**Comment by johnnypoll** [comment] 2016-05-12 08:50
I also have this issue, any workarounds or likely pending fix?
Thanks, John

**Comment by i-like-robots** [comment] 2016-05-12 15:59
Duplicate of https://github.com/i-like-robots/EasyZoom/issues/79

**Closed by i-like-robots** 2016-05-12 15:59 UTC

**Comment by johnnypoll** [comment] 2016-05-12 16:44
Hi Matt,
Is this awaiting an implementation? I am unclear on whether there is something I can do? I see you suggested a standard pinch zoom might be a better solution, but is there a way I can configure this?
Thanks
John

**Comment by i-like-robots** [comment] 2016-05-12 20:10
@johnnypoll I'm afraid I haven't implemented this. As discussed in the issue referenced I believe if it's going to be done it should be done properly. I've had no need to use this plugin for some time so I've lacked the motivation to do so.

That said, it's entirely possible to only initialise the plugin on mousestop or via a gesture - perhaps using a tool such as hammer.js to accurately recognise it.
