### ISSUE TITLE
Zooms in when user swipes to scroll

### ISSUE THREAD

**Issue by mfronczyk** [i-like-robots/EasyZoom#113] opened 2018-05-12 07:23 UTC
It'd ne nice if the library could stop zooming in when the user swipes to scroll the page starting from the photo. Maybe a different event should be used to trigger the zoom? Or, maybe it should start capturing events and zooming in when someone taps and holds for 200ms for example? Then swiping shouldn't fire zooming in in most cases.  We noticed it on iPhone 6, but it's probably in other browsers too.

**Comment by i-like-robots** [comment] 2018-08-20 10:33
Duplicate of #79

**Closed by i-like-robots** 2018-08-20 10:33 UTC
Labels: Feature request, Refinement
